#repo sync -c system/extras 
#repo sync -c platform/build
#repo sync -c build/soong
#repo sync -c build/blueprint 
#repo sync -c prebuilts/go/linux-x86 
#repo sync -c platform/external/golang-protobuf
#repo sync -c platform/prebuilts/build-tools
#repo sync -c platform/prebuilts/vndk/v28
#repo sync -c platform/system/tools/aidl
#repo sync -c platform/art
#repo sync -c platform/bionic
#repo sync -c platform/prebuilts/clang/host/linux-x86
#repo sync -c platofmr/prebuilts/
#repo sync -c platform/ndk
#repo sync -c platform/external/libcxx
#repo sync -c system/core
#repo sync -c system/tools/hidl
#repo sync -c test/vts-testcase/hal
#repo sync -c platform/hardware/interfaces
#repo sync -c kernel/configs
#repo sync -c platform/system/tools/xsdc
#repo sync -c platform/test/vts
#repo sync -c platform/system/sepolicy
#repo sync -c external/googletest
#repo sync -c platform/system/libhidl
#repo sync -c platform/system/libhwbinder
repo sync -c platform/external/protobuf
repo sync -c platform/libcore
repo sync -c platform/external/selinux
